language: rust
jobs:
  include:
    - rust: 1.37.0
      env:
      - ALL=' '
    - rust: stable
      env:
        - FEATURES='unstable quickcheck'
        - CHECKFMT=1
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
      - FEATURES='no_std'
    - rust: nightly
      env:
       - FEATURES='unstable quickcheck'
       - BENCH=1
branches:
  only:
    - master
before_script:
  - |
      if [ "${CHECKFMT}" == "1"]; then
        rustup component add rustfmt --toolchain stable
      fi
script:
  - |
      cargo build --verbose --no-default-features &&
      cargo test --verbose --no-default-features &&
      cargo build --verbose --features "$FEATURES" &&
      cargo test ${ALL:---all} --verbose --features "$FEATURES" &&
      if [ "${CHECKFMT}" == "1"]; then
        cargo +stable fmt -- --check
      fi

