language: rust
sudo: false
matrix:
  include:
    - rust: stable
      env:
      - FEATURES='quickcheck'
    - rust: beta
    - rust: nightly
    - rust: nightly
      env:
       - FEATURES='test quickcheck'
       - BENCH=1
script:
  - |
      cargo build --verbose --features "$FEATURES" &&
      cargo test --verbose --features "$FEATURES" &&
      ([ "$BENCH" != 1 ] || cargo bench --verbose --features "$FEATURES") &&
      cargo doc --verbose --features "$FEATURES"
